### ISSUE TITLE
Access to benign logs

### ISSUE THREAD

**Issue by insanitybit** [sbousseaden/EVTX-SAMPLES#3]
Would it be possible to get a dump of *all* of the logs, not just the ones with the attacks? The data is really useful as is, but having the full set of logs to tie together the benign and the attacker behaviors would be great for my use case.

**Comment by sbousseaden** [comment]
if you mean logs unrelated to an attack then no, each evtx contains max eventids that can serve to design detection logic per type of attack.

**Comment by insanitybit** [comment]
Yeah, I was talking about the logs unrelated to the attack. Alright, fair enough.
