### ISSUE TITLE
[Question] Any advice regarding how to contribute?

### ISSUE THREAD

**Issue by recvfrom** [sbousseaden/EVTX-SAMPLES#4]
Do you have any advice regarding how to contribute new evtx samples to this repo?  For instance, is there an easy way to know whether a set of event logs is already covered by another sample in the repo, making it not really worth adding?  And do you have a set of event IDs that aren't interesting and should always be excluded from new samples?  Thank you!

**Comment by sbousseaden** [comment]
It's not about eventids it's about their content, you can create a pull request that I can review and then proceed to excluding unnecessary events if any. Most important is to specify which attack trick it applies to.
