### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by shivam-bathla** [sbousseaden/EVTX-SAMPLES#5]
Hey guys,

Great work!
Just wanted to confirm, what is the license associated this project. I wanted to use these event logs for analysis in my personal project, so just wanted to be sure that there is no trouble using these logs for analysis.

Thanks.

**Comment by sbousseaden** [comment]
No problem at all, just mention the source in the references section of your project. Thanks!

**Comment by shivam-bathla** [comment]
Thanks.
