### ISSUE TITLE
Pentesting cheatsheets

### ISSUE THREAD

**Issue by jomivz** [sbousseaden/EVTX-SAMPLES#6]
Hi sbousseaden,

First thanks a lot for sharing your work. I guess it hours and hours of lab.

Your repo is a real good idea for blueteams and SOC. 
You give a nice try to cover the ATTA&CK matrix but some artefacts may have a different format than logs and evtx. For example, it can be PCAP files for an network scan / fingerprint.

In addition, it can be interesting when testing to know to generate those events.
I share sources for pentesting cheatsheets which can help covering some TTPs.

https://www.hackingarticles.in/penetration-testing/
http://projects.webappsec.org/w/page/13246978/Threat%20Classification (in the references)

I would be please to contribute to this repo.

BR

**Comment by sbousseaden** [comment]
Thanks Michel. I will try to add in the future more types of articafts (I've added one recently for IIS logs Rdp Tunneling https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Command%20and%20Control/Tunna_rdp_tunnel_IIS.log) soon will include pcap files for DNS Exfiltration, Bluekeep, Eternal-Blue ....

If you have some pcaps or WebServer logs you want to share please let me know.

BR

**Comment by federico22285** [comment]
Hey @sbousseaden  I would like to make you aware of this project, sadly most of your events cannot be converted in there, I was able to graph a couple. If you could correct them to be parsed in here, that, my friend, would be awesome :-)

https://github.com/yampelo/beagle
